# Generated by Django 5.0.1 on 2025-02-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=40),
        ),
    ]
