# Generated by Django 5.0.1 on 2025-02-14 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pics', to='myapp.event')),
            ],
        ),
    ]
