# Generated by Django 5.0.1 on 2025-02-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_eventpics'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='', upload_to='organizer/event_cover_images/'),
        ),
    ]
