# Generated by Django 5.0.1 on 2025-02-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_eventcategory_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='cat_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
