# Generated by Django 5.0.1 on 2025-02-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_eventcategory_cat_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_tickets', models.CharField(max_length=1)),
                ('total_amount', models.CharField(max_length=6)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='myapp.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user')),
            ],
            options={
                'db_table': 'event_tickets',
            },
        ),
    ]
