# Generated by Django 5.0.1 on 2025-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_eventtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
