# Generated by Django 5.0.1 on 2025-02-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_event_total_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtickets',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='myapp.event'),
        ),
    ]
