# Generated by Django 5.0.1 on 2025-02-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_eventtickets_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtickets',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='myapp.event'),
        ),
    ]
