# Generated by Django 5.0.1 on 2025-02-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_eventtickets_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='organizer/customize_event_cover_images/')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_events', to='myapp.organizer')),
            ],
            options={
                'db_table': 'customize_events',
            },
        ),
        migrations.CreateModel(
            name='CustomizeEventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/event_theme/')),
                ('price', models.CharField(max_length=10)),
                ('customize_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_event_pics', to='myapp.customizeevent')),
            ],
        ),
    ]
