# Generated by Django 5.0.1 on 2025-02-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customizeevent_customizeeventtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('suggestions', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_id', to='myapp.customizeeventtheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='myapp.user')),
            ],
            options={
                'db_table': 'event_request',
            },
        ),
    ]
