# Generated by Django 5.0.1 on 2025-02-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_eventrequest_location_eventrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='organizer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='organizer_id', to='myapp.organizer'),
        ),
    ]
