# Generated by Django 5.0.1 on 2025-02-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_eventrequest_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_id', to='myapp.organizer'),
        ),
    ]
